=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejerciciosComplejos/redHidrografica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="redHidrografica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rio" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fuente">
                                <xs:complexType>
                                    <xs:attribute name="latitud" type="xs:decimal"></xs:attribute>
                                    <xs:attribute name="longitud" type="xs:decimal"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="afluentes">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="afluente" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="fuente">
                                                        <xs:complexType>
                                                            <xs:attribute name="latitud"></xs:attribute>
                                                            <xs:attribute name="longitud"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id"></xs:attribute>
                                                <xs:attribute name="nombre"></xs:attribute>
                                                <xs:attribute name="longitud"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"></xs:attribute>
                        <xs:attribute name="nombre" type="xs:string"></xs:attribute>
                        <xs:attribute name="longitud" type="xs:integer"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejerciciosComplejos/redHidrografica.xml
<?xml version="1.0" encoding="UTF-8"?>
<redHidrografica
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="redHidrografica.xsd">
    <rio id="Rio001" nombre="Amazonas" longitud="7050">


        
        <fuente latitud="-10.282" longitud="-78.055"/>
        <afluentes>
            <afluente id="Afl001" nombre="Marañón" longitud="1500">
                <fuente latitud="-9.082" longitud="-77.202"/>
            </afluente>
            <afluente id="Afl002" nombre="Ucayali" longitud="1771">
                <fuente latitud="-11.352" longitud="-75.012"/>
            </afluente>
        </afluentes>
    </rio>
    <rio id="Rio002" nombre="Nilo" longitud="6650">
        <fuente latitud="2.268" longitud="33.634"/>
        <afluentes>
            <afluente id="Afl003" nombre="Atbara" longitud="805">
                <fuente latitud="12.708" longitud="35.832"/>
            </afluente>
            <afluente id="Afl004" nombre="Nilo Azul" longitud="1450">
                <fuente latitud="10.096" longitud="38.014"/>
            </afluente>
        </afluentes>
    </rio>
</redHidrografica>
