=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/Examen/coches.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="coches">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelo" type="xs:string"></xs:element>
                            <xs:element name="ano" type="xs:integer"></xs:element>
                            <xs:element name="precio" type="xs:decimal"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/Examen/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<coches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="coches.xsd">
    <coche>
        <marca>Toyota</marca>
        <modelo>Corolla</modelo>
        <ano>2020</ano>
        <precio>20000</precio>
    </coche>
    <coche>
        <marca>Ford</marca>
        <modelo>Mustang</modelo>
        <ano>2021</ano>
        <precio>35000.5</precio>
    </coche>
    <coche>
        <marca>Tesla</marca>
        <modelo>Model 3</modelo>
        <ano>2022</ano>
        <precio>45000</precio>
    </coche>
</coches>
