=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/Examen/olimpiadas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Olimpiadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Deportistas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Deportista" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
                                    <xs:attribute name="nombre" type="xs:string" use="required"></xs:attribute>
                                    <xs:attribute name="deporte" type="xs:string" use="optional"></xs:attribute>
                                    <xs:attribute name="paÃ­s" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Eventos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Evento" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Participa" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="dep" type="xs:IDREF"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
                                    <xs:attribute name="nombre" type="xs:string" use="required"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/Examen/olimpiadas.xml
<?xml version="1.0" encoding="UTF-8"?>
<Olimpiadas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="olimpiadas.xsd">
  <Deportistas>
    <Deportista id="dep1" nombre="John Doe" deporte="Atletismo" país="USA" />
    <Deportista id="dep2" nombre="Ana Smith" país="CAN" />
    <Deportista id="dep3" nombre="Lu Han" deporte="Gimnasia" país="CHN" />
    <Deportista id="dep4" nombre="Fan Yilin" deporte="Gimnasia" país="CHN" />
  </Deportistas>
  <Eventos>
    <Evento id="evento1" nombre="100m hombres">
      <Participa dep="dep1" />
    </Evento>
    <Evento id="evento2" nombre="200m mariposa mujeres">
      <Participa dep="dep2" />
    </Evento>
    <Evento id="evento3" nombre="Equipo de gimnasia mujeres">
      <Participa dep="dep3" />
      <Participa dep="dep4" />
    </Evento>
  </Eventos>
</Olimpiadas>
