=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejemplosXSDcomplejos/alumnos2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="escuela">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="edad" type="xs:int"/>
                            <xs:element name="cursos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="curso" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombreCurso" type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute name="calificacion" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejemplosXSDcomplejos/alumnos2.xml
<?xml version="1.0" encoding="UTF-8"?>
<escuela
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="alumnos2.xsd">
    <alumno id="A001">
        <nombre>Carlos Pérez</nombre>
        <edad>20</edad>
        <cursos>
            <curso calificacion="A">
                <nombreCurso>Matemáticas</nombreCurso>
            </curso>
            <curso calificacion="B">
                <nombreCurso>Literatura</nombreCurso>
            </curso>
        </cursos>
    </alumno>
    <alumno id="A002">
        <nombre>Lucía Gómez</nombre>
        <edad>22</edad>
        <cursos>
            <curso calificacion="A">
                <nombreCurso>Biología</nombreCurso>
            </curso>
            <curso calificacion="A">
                <nombreCurso>Química</nombreCurso>
            </curso>
        </cursos>
    </alumno>
</escuela>
