=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejemplosXSDcomplejos/itemsOficina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="inventario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="items">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="cantidad" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pedidos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pedido" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="itemRef" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="itemID" type="xs:IDREF"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== elenaac949/1DAM-Lenguaje-de-Marcas/Tercer trimestre-XML/4. XSD/ejemplosXSDcomplejos/itemsOficina.xml
<?xml version="1.0" encoding="UTF-8"?>
<inventario
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="itemsOficina.xsd">
    <items>
        <item id="IT001">
            <nombre>Plumas</nombre>
            <cantidad>100</cantidad>
        </item>
        <item id="IT002">
            <nombre>Papel A4</nombre>
            <cantidad>500</cantidad>
        </item>
        <item id="IT003">
            <nombre>Carpetas</nombre>
            <cantidad>200</cantidad>
        </item>
    </items>
    <pedidos>
        <pedido>
            <itemRef itemID="IT001"/>
            <itemRef itemID="IT002"/>
        </pedido>
        <pedido>
            <itemRef itemID="IT003"/>
        </pedido>
    </pedidos>
</inventario>
